server:
  port: 9412
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

spring:
  profiles:
    active: localPostgres
  autoconfigure:
    # whitelabel redirect disable. +@ ErrorController, Error redirecting.
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  secretKey: ENC(ppMHrRZzLlcV2TmsO32e7MkKNCtbnZ4E4zpW/REiqWWkfnj0ohTZMLkoZP/NdyzKkwp6bg8zYp1I8nwg8XxtjyCPu4EdbihRWxKJPDodKdY=)

springdoc:
  swagger-ui:
    tags-sorter: alpha
    default-models-expand-depth: 2
    operations-sorter: alpha
  show-login-endpoint: true
  enable-spring-security: true

puzzly:
  version: 1.0.3
  private:
    key: ENC(5CPnefCvPqOWL6FYkTwxY5CkHRqS27CrTH7qfpzEEwuVyaYZoDqOBYeViEtrfabSsPK5tVJJ71ekChRIwT88tzIE8BBxmQsMc/y8ajbgULo=)
  datago:
    encoding: ENC(Rb+tcSkUi8t9VepHVoagIaxD1nIwKFSbZeKUbotC4oBbkF/+xuww1lRtHP2chQro0pOrPuJ1BY7u/k+oK6tTE9zRK81bqe0xloE9451UY8S+m0vs+K6IEhUlTnNQ+R7lGRMc1r9mgOF1FZ7+MUK4Rg==)
    decoding: ENC(/6unzWIpnNY+qii6hEyQNhiY03YLQMztJsHxLiVK8BlI7Rt2Hif4izhD9adEjXzJWpsKGRXK2xuvSixPKDbr+yYL00F3ZN1ynlbUlhA/TEkiq1k/MoXw5m2FOvERaclBo19YOI6qYx8=)
#--- localPostgres
---
spring:
  config:
    activate:
      on-profile: localPostgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      # auto find dialect at hibernate6
      #dialect: org.hibernate.dialect.PostgreSQLDialect
    #show-sql: false
    generate-ddl: true
    defer-datasource-initialization: true
    #properties:
    #  hibernate:
    #    format_sql: true

  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:7220/puzzly?characterEncoding=utf8&&allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:7220/puzzly?characterEncoding=utf8&&allowMultiQueries=true
    username: ENC(nvF/CuzlEIuUlC69v08Q1Q==)
    password: ENC(J9GWfqblNgjCYDx6RHrmLt1Yyx5t1SxxojI0YcDavRg=)

  data:
    redis:
      host: localhost
      port: 7230
      password: ENC(Mz63mC8Ggz5AreNEJQbGjUyO0assAFscXqEx0NQzeW0=)

puzzly:
  filePath: /Users/junhoon.lee/sideP/PuzzlyFile
  swagger-ui:
    server-url: http://localhost:9412
logging:
  level:
    root: info
    #org:
      #hibernate:
        #orm:
        #  jdbc:
        #    bind: trace
        #type:
        #  descriptor:
        #    sql: trace
#--- devPostgres
---
spring:
  config:
    activate:
      on-profile: devPostgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:7220/puzzly?characterEncoding=utf8&&allowMultiQueries=true
    username: ENC(nvF/CuzlEIuUlC69v08Q1Q==)
    password: ENC(J9GWfqblNgjCYDx6RHrmLt1Yyx5t1SxxojI0YcDavRg=)
puzzly:
  filePath: /opt/PuzzlyFile
  swagger-ui:
    server-url: http://146.56.118.235:9412
logging:
  level:
    root: info